Compile for RPI
KGrzeg/ohNet pull request #3
Opened 2022-11-14 16:28 UTC by KGrzeg

2022-11-15 12:23 UTC, DoomHammer commented on CMakeLists.txt
> +    if(${CMAKE_CROSSCOMPILING})
Do you think we only need it when cross-compiling? I'd assume we need threads universally across all platforms (unless proven otherwise).

2022-11-15 12:25 UTC, DoomHammer requested changes

2022-11-15 12:25 UTC, DoomHammer commented on CMake/Toolchain-RaspberryPi.cmake
> +SET(CMAKE_FIND_ROOT_PATH $ENV{HOME}/rpi/rootfs)
This assumes we already have such a directory. Either something in README on how to set up the project would help or some automated script that can get that for us.

Also, this looks like a nice thing to turn into variable as some may have it in ~/rpi, others in ~/projects, yet others in /var/lib/rpi

2022-11-15 14:22 UTC, KGrzeg commented on CMakeLists.txt
> +    if(${CMAKE_CROSSCOMPILING})
In the past we compiled the app for other platforms easly. Explicit indication of threads was neede only for Raspberry.

2022-11-17 09:50 UTC, DoomHammer commented on CMakeLists.txt
> +    if(${CMAKE_CROSSCOMPILING})
But this will apply even when cross-compiling from Linux to Windows with MinGW, am I right?

2022-11-25 14:37 UTC, KGrzeg commented on CMakeLists.txt
> +    if(${CMAKE_CROSSCOMPILING})
Yea, that make sense. I created a new variable to distinguish between default cross-compilation with Linux target and with our raspberry.

2022-11-25 15:28 UTC, DoomHammer approved these changes

2022-11-25 15:28 UTC, merged