Fetch dependencies from conan if that is possible
KGrzeg/ohNet pull request #4
Opened 2022-11-25 14:21 UTC by KGrzeg

2022-11-25 15:29 UTC, DoomHammer commented
It looks like it could use a rebase

2022-11-26 14:24 UTC, KGrzeg commented
That's better

2022-11-27 09:37 UTC, DoomHammer commented on CMakeLists.txt
> +conan_basic_setup()
The currently preferred way is to use Conan with find_package generator and use `find_packages` and `target_link_libraries` individually for each imported lib.

See for reference: https://github.com/PacktPublishing/Software-Architecture-with-Cpp/blob/master/Chapter08/customer/CMakeLists.txt#L21

2022-11-27 09:43 UTC, DoomHammer commented on default.nix
> +    # conan install manually the latest version!
```
 shellHook = ''
    [ ! -d venv ] && python -m virtualenv venv
    source venv/bin/activate
    pip install conan==1.54.0
  '';
```

2022-11-27 09:43 UTC, DoomHammer requested changes
We should use the `CMakeDeps` Conan generator as the other one is deprecated.

2022-11-29 12:19 UTC, DoomHammer approved these changes

2022-11-29 12:20 UTC, merged